"""baseline: full schema as of introducing Alembic

Revision ID: 0001_baseline
Revises:
Create Date: 2026-10-04

Every table and column this migration creates already existed in some real
database before Alembic replaced the hand-written ``ALTER TABLE`` patches in
``db._ADDED_COLUMNS`` -- see ``budget_tracker.db.init_db`` for how such a database
is walked to exactly this state (by that same patch logic, kept for this one-time
path) and then stamped at this revision without ever running the code below.

This is autogenerated output (``alembic revision --autogenerate`` against an empty
database, target ``Base.metadata``), copied in by hand rather than left as a live
``Base.metadata.create_all()`` call. A baseline has to be a frozen snapshot of the
schema on the day it was cut: once a later migration adds a table, a baseline that
still called ``create_all`` against the *current* models would create that table
too, and the later migration creating it again would fail on any database replayed
from empty -- and on an already-versioned database, the empty-diff autogenerate
would see nothing to add and silently skip the table in the first place.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_baseline"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["category.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value", name="uq_category_value"),
    )
    op.create_table(
        "csv_format",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("signature", sa.String(), nullable=False),
        sa.Column("posted_date_column", sa.String(), nullable=False),
        sa.Column("description_column", sa.String(), nullable=False),
        sa.Column("date_formats", sa.String(), nullable=False),
        sa.Column("amount_style", sa.String(), nullable=False),
        sa.Column("dedup_columns", sa.String(), nullable=False),
        sa.Column("txn_date_column", sa.String(), nullable=True),
        sa.Column("category_column", sa.String(), nullable=True),
        sa.Column("debit_column", sa.String(), nullable=True),
        sa.Column("credit_column", sa.String(), nullable=True),
        sa.Column("amount_column", sa.String(), nullable=True),
        sa.Column("account_column", sa.String(), nullable=True),
        sa.Column("account_prefix", sa.String(), nullable=False),
        sa.Column("invert_amount", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "currency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("decimal_places", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value"),
    )
    op.create_table(
        "exchange_rate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("base", sa.String(), nullable=False),
        sa.Column("quote", sa.String(), nullable=False),
        sa.Column("rate", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "day", "base", "quote", "source", name="uq_exchange_rate_day_base_quote_source"
        ),
    )
    op.create_table(
        "sync_connection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "kind", name="uq_tag_name_kind"),
    )
    op.create_table(
        "vendor_name",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value"),
    )
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("opening_balance_minor", sa.Integer(), nullable=True),
        sa.Column("opening_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["currency_id"], ["currency.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "category_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pattern", sa.String(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pattern"),
    )
    op.create_table(
        "trip_bucket",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("bucket", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_table(
        "vendor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("vendor_name_id", sa.Integer(), nullable=True),
        sa.Column("vendor_name_source", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["vendor_name_id"], ["vendor_name.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "vendor_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pattern", sa.String(), nullable=False),
        sa.Column("vendor_name_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["vendor_name_id"], ["vendor_name.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pattern"),
    )
    op.create_table(
        "import",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("sync_connection_id", sa.Integer(), nullable=True),
        sa.Column("source_file", sa.String(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column(
            "imported_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"]),
        sa.ForeignKeyConstraint(["sync_connection_id"], ["sync_connection.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sync_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column("remote_id", sa.String(), nullable=False),
        sa.Column("remote_name", sa.String(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("synced_through", sa.Date(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("last_status", sa.String(), nullable=True),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"]),
        sa.ForeignKeyConstraint(["connection_id"], ["sync_connection.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", name="uq_sync_account_account"),
        sa.UniqueConstraint(
            "connection_id", "remote_id", name="uq_sync_account_connection_remote"
        ),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("import_id", sa.Integer(), nullable=True),
        sa.Column("vendor_id", sa.Integer(), nullable=True),
        sa.Column("posted_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("raw_description", sa.String(), nullable=False),
        sa.Column("value_minor", sa.Integer(), nullable=False),
        sa.Column("transfer_group_id", sa.Integer(), nullable=True),
        sa.Column("category_source", sa.String(), nullable=False),
        sa.Column("import_hash", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"]),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"]),
        sa.ForeignKeyConstraint(["currency_id"], ["currency.id"]),
        sa.ForeignKeyConstraint(["import_id"], ["import.id"]),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendor.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_hash"),
    )
    op.create_table(
        "transaction_tag",
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("transaction_id", "tag_id"),
    )


def downgrade() -> None:
    op.drop_table("transaction_tag")
    op.drop_table("transactions")
    op.drop_table("sync_account")
    op.drop_table("import")
    op.drop_table("vendor_rule")
    op.drop_table("vendor")
    op.drop_table("trip_bucket")
    op.drop_table("category_rule")
    op.drop_table("account")
    op.drop_table("vendor_name")
    op.drop_table("tag")
    op.drop_table("sync_connection")
    op.drop_table("exchange_rate")
    op.drop_table("currency")
    op.drop_table("csv_format")
    op.drop_table("category")
