"""add budget_amount

Revision ID: 0002_add_budget_amount
Revises: 0001_baseline
Create Date: 2026-10-04

Adds the one table the monthly budget feature needs -- see ``budget_tracker.budget``.
Autogenerated against ``models.BudgetAmount`` and reviewed by hand: the FK's
``ondelete="CASCADE"``, the three-column unique constraint, and ``created_at``'s
server default all came through correctly from the model and needed no fixing up.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002_add_budget_amount"
down_revision: Union[str, Sequence[str], None] = "0001_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "budget_amount",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "month", "kind", "category_id", name="uq_budget_amount_month_kind_category"
        ),
    )


def downgrade() -> None:
    op.drop_table("budget_amount")
